module.exports = [
    "Shinobu Kocho",
    "The Hashira",
    "Love & Mist Hashira vs Upper Moons",
    "Nezuko",
    "Inosuke Hashibira",
    "Nezuko Kamado",
    "Zenitsu Agatsuma",
    "Giyu Tomioka",
    "Shinobu Kocho",
    "Kyoujurou Rengoku",
    "Tanjiro Kamado",
    "Muzan Kibutsuji",
    "Rengoku vs Akaza",
    "Gyokko",
    "Nezuko Kamado",
    "Enmu",
    "Genya Shinazugawa",
    "Gyomei Himejima",
    "Zenitsu Agatsuma",
    "Rui",
    "Mitsuri Kanroji",
    "Obanai Iguro",
    "Sanemi Shinazugawa",
    "Muichiro Tokito",
    "Kanao Tsuyuri",
    "Inosuke Hashibira",
    "Hantengu, Zohakuten, Urogi, Aizetsu, Karaku and Sekido",
    "Shinobu Kocho",
    "Daki",
    "Kyojuro Rengoku",
    "Gyutaro",
    "Sabito & Makomo",
    "Giyu Tomioka",
    "Tengen Uzui",
    "Tanjiro Kamado",
    "Gyokko",
    "Gyuutarou and Daki",
    "Shinobu",
    "Kyoujurou Rengoku",
    "Muzan Kibutsuji",
    "Tanjiro and Nezuko",
    "Rui",
    "Tanjirou and Kyojuro",
    "Sanemi Shinazugawa",
    "Sakonji Urokodaki",
    "Genya Shinazugawa",
    "Uzui Tengen",
    "Gyomei Himejima",
    "Obanai Iguro",
    "Muichiro Tokito",
    "Tanjiro and Tengen",
    "Daki",
    "Zenitsu Agatsuma",
    "Mitsuri Kanroji",
    "Giyu Tomioka",
    "Inosuke Hashibira",
    "Tanjiro Kamado",
    "Nezuko Kamado",
    "Tanjiro, Zenitsu, and Inosuke",
    "Hantengu",
    "Gyokko",
    "Genya Shinazugawa",
    "Sabito and Makomo",
    "Yahaba",
    "Akaza",
    "Susamaru",
    "Kanao Tsuyuri",
    "Inosuke Hashibira",
    "Zenitsu Agatsuma",
    "Muzan Kibutsuji",
    "Tanjiro Kamado",
    "Muichiro Tokito",
    "Tengen Uzui",
    "Shinobu Kocho",
    "Kagaya Ubuyashiki",
    "Daki",
    "Mitsuri Kanroji",
    "Nezuko Kamado",
    "Gyuutaro",
    "Yushiro",
    "Tamayo",
    "Douma",
    "Hand Demon",
    "Kyoujurou Rengoku",
    "Tengen's Family",
    "Giyu Tomioka",
    "Douma",
    "Gyomei Himejima",
    "Nezuko Kamado",
    "Muzan Kibutsuji",
    "Aoi Kanzaki",
    "Akaza",
    "Enmu",
    "Mitsuri Kanroji",
    "Sabito",
    "Makomo",
    "Inosuke Hashibira",
    "Daki",
    "Giyu Tomioka",
    "Shinobu Kocho",
    "Gyuutarou",
    "Zenitsu Agatsuma",
    "Tanjiro and Nezuko",
    "Kagaya Ubuyashiki",
    "Tengen Uzui",
    "Sanemi Shinazugawa",
    "Sakonji Urokodaki",
    "Obanai Iguro",
    "Muichiro Tokito",
    "Tanjiro Kamado",
    "Konosuba",
    "Megumin",
    "Aqua",
    "Kazuma Satou",
    "Darkness",
    "Megumin",
    "Aqua",
    "Aqua",
    "Wiz",
    "Kazuma and Megumin",
    "Yunyun",
    "Aqua, Megumin, and Darkness",
    "Megumin",
    "Kazuma Satou",
    "Yunyun",
    "Kazuma's Party",
    "Megumin and Yunyun",
    "Darkness",
    "Aqua",
    "Aqua and Megumin",
    "Megumin",
    "Chris",
    "Yunyun",
    "Kazuma Satou",
    "Megumin",
    "Darkness",
    "Lean",
    "Rein Chelka",
    "Beldia",
    "Aqua",
    "Wiz",
    "Vanir",
    "Komekko",
    "Sylvia",
    "Chomusuke",
    "Yunyun",
    "Megumin",
    "Aqua",
    "Sena",
    "Satou Kazuma",
    "Wiz",
    "Chris",
    "Darkness",
    "Rukia",
    "Kuchiki Byakuya",
    "Ulquiorra Cifer",
    "Ichigo Kurosaki",
    "Grimmjow Jaegerjaquez",
    "Kenpachi Zaraki",
    "Kisuke Urahara",
    "Ikkaku Madarame",
    "Shunsui Kyoraku",
    "Shuhei Hisagi",
    "Mayuri Kurotsuchi",
    "Nelliel Tu Oderschvank",
    "Retsu Unohana",
    "Yhwach",
    "Kukaku Shiba",
    "Ukitake and Kyoraku",
    "Gin Ichimaru",
    "Genryusai Shigekuni Yamamoto",
    "Rangiku Matsumoto",
    "Kaname Tosen",
    "Shinji Hirako",
    "Kenpachi Zaraki",
    "Grimmjow Jeagerjaques",
    "Aizen Sosuke",
    "Rukia Kuchiki",
    "Ulquiorra Cifer",
    "Toshiro Hitsugaya",
    "Ichigo Kurosaki",
    "Rukia and Ichigo",
    "Kisuke Urahara",
    "Gin Ichimaru and Sosuke Aizen",
    "Nemu Kurotsuchi",
    "Gin Ichimaru",
    "Kaname Tōsen",
    "Ouetsu Nimaiya",
    "Mayuri Kurotsuchi",
    "Hitsugaya Toshiro",
    "Rukia Kuchiki",
    "Renji Abarai",
    "Renji and Byakuya",
    "Grimmjow Jaegerjaquez",
    "Yasutora Sado",
    "Kenpachi Zaraki & Yachiru Kusajishi",
    "Shinji Hirako",
    "Kisuke Urahara & Yoruichi Shihoin",
    "Soi Fon",
    "Kukaku Shiba",
    "Izuru Kira",
    "Kirio Hikifune",
    "Shunsui Kyoraku",
    "Uryu Ishida",
    "Coyote Starrk",
    "Yoruichi Shihoin",
    "Sosuke Aizen",
    "Ichigo Kurosaki",
    "Rangiku Matsumoto",
    "Ulquiorra Cifer",
    "Nelliel Tu Odelschwanck",
    "Orihime, Sado And Uryuu",
    "Senjumaru Shutara",
    "Soi Fon & Yoruichi Shihoin",
    "Retsu Unohana",
    "Orihime Inoue",
    "Kenpachi Zaraki",
    "Juushirou Ukitake",
    "Genryusai Yamamoto",
    "Gin Ichimaru",
    "Toshiro Hitsugaya",
    "Ganju and Kukaku",
    "Senjumaru Shutara",
    "Grimmjow Jaegerjaquez",
    "Kenpachi Zaraki",
    "Ulquiorra Cifer",
    "Shunsui Kyoraku",
    "Rukia Kuchiki",
    "Rangiku Matsumoto",
    "Nelliel Tu Odelschwanck",
    "Retsu Unohana",
    "Byakuya Kuchiki",
    "Riruka Dokugamine",
    "Orihime Inoue",
    "Isshin Kurosaki",
    "Coyote Starrk",
    "Yhwach",
    "Isshin and Masaki",
    "Bambietta Basterbine",
    "Ichigo Kurosaki",
    "Sosuke Aizen",
    "Masaki Kurosaki",
    "Kisuke Urahara",
    "Ichigo, Rukia, Orihime, Renji, & Sado",
    "Shinji Hirako",
    "Sajin Komamura",
    "Yoruichi Shihoin",
    "Jushiro Ukitake",
    "Izuru Kira",
    "Ichigo Kurosaki",
    "Nemu Kurotsuchi",
    "Nelliel Tu Oderschvank",
    "Byakuya Kuchiki",
    "Yoruichi Shihouin",
    "White Ichigo",
    "Kukaku Shiba",
    "Yasutora Sado",
    "Coyote Starrk",
    "Genryusai Yamamoto",
    "Orihime Inoue",
    "Kisuke Urahara",
    "Tier Harribel",
    "Senjumaru Shutara",
    "Zangetsu",
    "Sajin Komamura",
    "Shinji Hirako",
    "Soi Fon",
    "Grimmjow Jaegerjaquez",
    "Rangiku Matsumoto",
    "Riruka Dokugamine",
    "Bambietta Basterbine",
    "Kensei Muguruma",
    "Nnoitra Gilga",
    "Szayelaporro Granz",
    "Askin Nakk Le Vaar",
    "Barragan Louisenbairn",
    "Toshiro Hitsugaya",
    "Yachiru Kusajishi",
    "As Nodt",
    "Sosuke Aizen",
    "Ulquiorra Cifer",
    "Kenpachi",
    "Ikkaku Madarame",
    "Yumichika Ayasegawa",
    "Hanataro Yamada",
    "Shuhei Hisagi",
    "Isane Kotetsu",
    "Mayuri Kurotsuchi",
    "Yukio Hans Vorarlberna",
    "Rukia Kuchiki",
    "Shunsui Kyoraku",
    "Retsu Unohana",
    "Ryuken Ishida",
    "Shukuro Tsukishima",
    "Gin Ichimaru",
    "Renji Abarai",
    "Jugram Haschwalth",
    "Kuugo Ginjou",
    "Kon",
    "Yhwach",
    "Yuuki x Asuna",
    "Sinon",
    "Eugeo",
    "Kirito",
    "Kirito and Asuna",
    "Alice Zuberg",
    "Yuna",
    "Kirito",
    "Quinella",
    "Eugeo",
    "Konno Yuuki",
    "Silica",
    "Bercouli",
    "Emperor Vecta",
    "Klein",
    "Leafa",
    "Sinon",
    "Asuna Yuuki",
    "Alice Zuberg",
    "Asuna Yuuki",
    "Silica",
    "Lisbeth",
    "Lisbeth, Silica and Pina",
    "Asuna and Yui",
    "Eugeo",
    "Asuna and Mito",
    "Eiji Nochizawa",
    "Alice Zuberg",
    "Sinon",
    "Leafa",
    "Yuna Shigemura",
    "Yui",
    "Sinon and Kirito",
    "Konno Yuuki",
    "Kirito and Eugeo",
    "Mito",
    "Eugeo, Kirito and Alice",
    "Asuna and Yuuki",
    "Kirito",
    "Sterben",
    "Asuna and Alice",
    "Klein",
    "Eugeo and Alice",
    "Asuna Yuuki",
    "Ronye and Tiese",
    "Yuna and Eiji",
    "Heathcliff",
    "Cardinal",
    "Agil",
    "Quinella",
    "Kirito and Asuna",
    "Rosalia",
    "Eugeo",
    "Kirito",
    "Quinella",
    "Asuna Yuuki",
    "Tiese Shtolienen",
    "Leafa",
    "Agil",
    "Yuna",
    "Thor",
    "Jun",
    "Kyouko Yuuki",
    "Lipia Zancale",
    "Tonky",
    "Sachi",
    "Higa Takeru",
    "Silica",
    "Argo",
    "Lisbeth",
    "Selka Zuberg",
    "Scheta Synthesis Twelve",
    "Bercouli Synthesis One",
    "Sortiliena Serlut",
    "Linel and Fizel",
    "Iskahn",
    "Gabriel Miller",
    "Aki Natsuki",
    "Mito",
    "Sinon",
    "Koujiro Rinko",
    "Ronye Arabel",
    "Keita",
    "Yui",
    "Alice Zuberg",
    "Kirito",
    "Ronye Arabel",
    "Sterben",
    "Asuna Yuuki",
    "Tiese Shtolienen",
    "Silica",
    "Selka Zuberg",
    "Mito",
    "Alice Zuberg",
    "Leafa",
    "Lisbeth",
    "Silica and Pina",
    "Tetsuo",
    "Bercouli",
    "Ducker",
    "Klein",
    "Yuna",
    "Yui",
    "Yuuki Konno",
    "Eiji Nochizawa",
    "Fanatio",
    "Heathcliff",
    "Sinon",
    "Eugeo",
    "Quinella",
    "L Lawliet",
    "Light and Ryuk",
    "Light",
    "L Lawliet",
    "Misa Amane",
    "Ryuk",
    "Mihael Keehl",
    "Nate River",
    "Light Yagami",
    "Nate River",
    "Ryuk",
    "Misa Amane",
    "Light Yagami",
    "L Lawliet",
    "Touta Matsuda",
    "Mello",
    "Raye Penber",
    "Teru Mikami",
    "Rem",
    "Watari",
    "Shuichi Aizawa",
    "L Lawliet",
    "Shuichi Aizawa",
    "Raye Penber",
    "Soichiro Yagami",
    "Touta Matsuda",
    "Kanzo Mogi",
    "Kiyomi Takada",
    "Ryuk",
    "Nate River",
    "Light Yagami",
    "Diluc",
    "Zhongli",
    "Paimon",
    "Venti",
    "Hu Tao",
    "Genshin Impact",
    "Mona",
    "Nahida",
    "Raiden Shogun",
    "Paimon",
    "Yae Miko",
    "Yoimiya Naganohara",
    "Hu Tao",
    "Shenhe",
    "Kokomi Sangonomiya",
    "Xiao",
    "Venti",
    "Zhongli",
    "Ningguang",
    "Neuvillette",
    "Ganyu",
    "Raiden Shogun",
    "Xingqiu",
    "Emilie",
    "Sucrose",
    "Amber",
    "Kaveh",
    "Kokomi Sangonomiya",
    "Jean",
    "Baizhu",
    "Xiangling",
    "Freminet",
    "Yaoyao",
    "Sayu",
    "Kirara",
    "Wanderer",
    "Xiao",
    "Arlecchino",
    "Razor",
    "Charlotte",
    "Chiori",
    "Layla",
    "Rosaria",
    "Nilou",
    "Klee",
    "Venti",
    "Bennett",
    "Yanfei",
    "Navia",
    "Collei",
    "Yae Miko",
    "Qiqi",
    "Shenhe",
    "Yun Jin",
    "Xinyan",
    "Diona",
    "Noelle",
    "Beidou",
    "Kaeya",
    "Fischl",
    "Chongyun",
    "Eula",
    "Dehya",
    "Zhongli",
    "Keqing",
    "Yoimiya Naganohara",
    "Barbara",
    "Ningguang",
    "Lisa",
    "Ayaka Kamisato",
    "Gorou",
    "Albedo",
    "Cyno",
    "Kazuha Kaedehara",
    "Furina",
    "Yelan",
    "Nahida",
    "Furina",
    "Wriothesley",
    "Yoimiya and Kazuha",
    "Lynette",
    "Aether",
    "Mualani",
    "Yelan",
    "Neuvillette",
    "Freminet",
    "Lumine",
    "Nilou",
    "Cyno",
    "Thoma",
    "Sayu",
    "Faruzan",
    "Lyney",
    "Raiden and Yae",
    "Emilie",
    "Raiden Shogun",
    "Candace",
    "Dori",
    "Albedo and Klee",
    "Kokomi Sangonomiya",
    "Xinyan",
    "Sara Kujou",
    "Xiangling",
    "Xingqiu",
    "Barbara and Jean",
    "Kirara",
    "Yanfei",
    "Sucrose",
    "Amber",
    "Klee and Yoimiya",
    "Xiangling and Hu Tao",
    "Kaveh",
    "Baizhu",
    "Ayato Kamisato",
    "Arlecchino",
    "Venti",
    "Xiao",
    "Xiangling and Chongyun",
    "Sucrose and Collei",
    "Lumine and Xiangling",
    "Aether and Albedo",
    "Albedo",
    "Tighnari",
    "Collei",
    "Chiori",
    "Itto and Shinobu",
    "Yun Jin and Xinyan",
    "Sayu and Yoimiya",
    "Yae Miko",
    "Kazuha and Beidou",
    "Rosaria",
    "Jean",
    "Kazuha Kaedehara",
    "Yoimiya Naganohara",
    "Yaoyao and Qiqi",
    "Keqing and Xiangling",
    "Ayaka and Thoma",
    "Ganyu and Xiao",
    "Gaming",
    "Yoimiya and Ayaka",
    "Keqing and Ganyu",
    "Yaoyao",
    "Dehya",
    "Heizou Shikanoin",
    "Xianyun",
    "Itto Arataki",
    "Ganyu",
    "Noelle",
    "Lumine and Aether",
    "Alhaitham",
    "Diluc and Kaeya",
    "Hu Tao",
    "Ningguang and Beidou",
    "Chevreuse",
    "Shenhe",
    "Yun Jin",
    "Gorou",
    "Eula",
    "Qiqi",
    "Bennett",
    "Mona",
    "Diluc",
    "Tartaglia",
    "Razor",
    "Ningguang",
    "Keqing",
    "Fischl",
    "Chongyun",
    "Zhongli",
    "Ayaka Kamisato",
    "Kaeya",
    "Navia",
    "Beidou",
    "Barbara",
    "Diona",
    "Klee",
    "Paimon",
    "Lisa",
    "Amber and Lumine",
    "Ayato and Ayaka",
    "Layla",
    "Shinobu Kuki",
    "Charlotte",
    "Wanderer",
    "Nahida",
    "Eula and Amber",
    "Lumine and Nilou",
    "Lynette and Lyney",
    "Abyss Herald",
    "Guoba",
    "Andrius",
    "Dvalin",
    "Rhodeia of Loch",
    "Azhdaha",
    "Beisht",
    "Osial",
    "Thunder Manifestation",
    "Shiki Taishou",
    "Mountain Shaper",
    "Moon Carver",
    "Cloud Retainer",
    "Primo Geovishap",
    "Ruin Guard",
    "Ruin Grader",
    "Thundercraven Rifthound",
    "Rockfond Rifthound",
    "Frostarm Lawachurl",
    "Thunderhelm Lawachurl",
    "Stonehide Lawachurl",
    "Jadeplume Terrorshroom",
    "Ruin Hunter",
    "Geovishap",
    "Electro Regisvine",
    "Cryo Hypostasis",
    "Hydrogunner Legionnaire",
    "Ruin Serpent",
    "Madame Ping",
    "Cryogunner Legionnaire",
    "Katheryne",
    "Eye of the Storm",
    "Golden Wolflord",
    "Cryo Regisvine",
    "Pyro Regisvine",
    "Perpetual Mechanical Array",
    "Hydro Abyss Mage",
    "Electro Abyss Mage",
    "Cryo Abyss Mage",
    "Electro Hypostasis",
    "Unusual Hilichurl",
    "Mitachurl",
    "Electro Cicin Mage",
    "Ruin Destroyer",
    "Ruin Scout",
    "Abyss Lector: Fathomless Flames",
    "Abyss Lector: Violet Lightning",
    "Abyss Herald: Wicked Torrent",
    "Ruin Defender",
    "Geo Hypostasis",
    "Pyro Abyss Mage",
    "Maguu Kenki",
    "Hydro Hypostasis",
    "Pyro Hypostasis",
    "Ruin Cruiser",
    "Anemo Hypostasis",
    "Rhodeia Of Loch",
    "Kazari",
    "Mirror Maiden",
    "Taroumaru",
    "Chevreuse",
    "Kinich and Ajaw",
    "Xilonen"
];

